/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nikolai Jonasson (https://sketchfab.com/nikolaijonasson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/female-marble-statue-polished-but-old-41b024813afd49fb827d942219d89b93
title: Female Marble Statue (Polished but old)
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF, useTexture, shaderMaterial } from "@react-three/drei";
import { useFrame, extend, useThree } from "@react-three/fiber";
import PaintedFragment from "../shaders/paint/fragment.glsl";
import PaintedVertex from "../shaders/paint/vertex.glsl";
import graffitiTexture from "/textures/graffiti.jpg";
console.log(graffitiTexture);

const PaintedShaderMaterial = shaderMaterial(
	{
		uTime: 0,
		lightPos: new THREE.Vector3(),
		graffitiTexture: new THREE.TextureLoader().load(graffitiTexture),
		cameraPos: new THREE.Vector3(),
	},
	PaintedVertex,
	PaintedFragment
);
extend({ PaintedShaderMaterial });

export function Painted(props) {
	const camera = useThree((state) => state.camera);
	console.log("camera pos", camera);

	const paintedShaderMaterialRef = useRef();

	// console.log(femaleVibrantShaderMaterialRef.current)

	useFrame((state, delta) => {
		paintedShaderMaterialRef.current.uTime += delta;
		paintedShaderMaterialRef.current.cameraPos = camera.position;
	});

	const { lightPos } = { ...props };

	console.log(lightPos);
	console.log(props);
	console.log("camera pos", camera);
	return (
		<paintedShaderMaterial
			ref={paintedShaderMaterialRef}
			side={THREE.DoubleSide}
			lightPos={lightPos}
			// abstractTexture={abstractTexture}
		/>
	);
}
