/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jeant_220 (https://sketchfab.com/juanfranciscotorresvicuna)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/male-human-a-pose-ac9555358aa94532863d9d7ee705dd21
title: Male Human A pose
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Pebbles(props) {
const pebbleShaderMaterialRef = useRef()

	const [
		pebblesTextureDiff,
		pebblesTextureHeight,
		pebblesTextureRough,
		pebblesTextureNormalMap,
	] = useTexture([
		"/textures/pebbles/PebblesI3_diffuse.jpg",
		"/textures/pebbles/PebblesI2_height.jpg",
		"/textures/pebbles/PebblesI2_roughness.jpg",
		"/textures/pebbles/PebblesI2_normal.jpg",
	]);




  return (

    
          			<meshStandardMaterial
						ref={pebbleShaderMaterialRef}
							map={pebblesTextureDiff}
							roughnessMap={pebblesTextureRough}
							displacementMap={pebblesTextureHeight}
							normalMap={pebblesTextureNormalMap}
							displacementScale={0.1}
							displacementBias={-.055}
							map-repeat={[1.5, 1.5]}
							map-wrapS={THREE.RepeatWrapping}
							map-wrapT={THREE.RepeatWrapping}
							displacementMap-wrapS={THREE.RepeatWrapping}
							displacementMap-wrapT={THREE.RepeatWrapping}
							roughnessMap-wrapS={THREE.RepeatWrapping}
							roughnessMap-wrapT={THREE.RepeatWrapping}
							normalMap-wrapS={THREE.RepeatWrapping}
							normalMap-wrapT={THREE.RepeatWrapping}
						/>

  );
}

