/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jeant_220 (https://sketchfab.com/juanfranciscotorresvicuna)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/male-human-a-pose-ac9555358aa94532863d9d7ee705dd21
title: Male Human A pose
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Tribal(props) {
	const [
		tribalTextureDiff,
		tribalTextureHeight,
		tribalTextureMetal,
		tribalTextureNormalMap,
	] = useTexture([
		"/textures/tribal/222_diffuseOriginal.jpg",
		"/textures/tribal/222_height.jpg",
		"/textures/tribal/222_metallic.jpg",
		"/textures/tribal/222_normal.jpg",
	]);

	return (
		<meshStandardMaterial
			map={tribalTextureDiff}
			metalnessMap={tribalTextureMetal}
			displacementMap={tribalTextureHeight}
			normalMap={tribalTextureNormalMap}
			displacementScale={0.1}
			displacementBias={-0.02}
			map-repeat={[3, 3]}
			map-wrapS={THREE.RepeatWrapping}
			map-wrapT={THREE.RepeatWrapping}
			displacementMap-wrapS={THREE.RepeatWrapping}
			displacementMap-wrapT={THREE.RepeatWrapping}
			metalnessMap-wrapS={THREE.RepeatWrapping}
			metalnessMap-wrapT={THREE.RepeatWrapping}
			normalMap-wrapS={THREE.RepeatWrapping}
			normalMap-wrapT={THREE.RepeatWrapping}
		/>
	);
}
